# Generated by Django 5.0.6 on 2024-06-25 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(db_column='Id_Estado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(db_column='Id_Pais', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
            ],
            options={
                'db_table': 'pais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TContribuyente',
            fields=[
                ('id_tcont', models.AutoField(db_column='Id_TCont', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 't_contribuyente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TDocumento',
            fields=[
                ('id_tdoc', models.AutoField(db_column='Id_TDoc', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 't_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(db_column='Id_Municipio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('id_estado', models.ForeignKey(blank=True, db_column='Id_Estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.estado')),
            ],
            options={
                'db_table': 'municipio',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='id_pais',
            field=models.ForeignKey(blank=True, db_column='Id_Pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.pais'),
        ),
    ]
