# Generated by Django 5.0.6 on 2024-06-25 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tuser', models.AutoField(db_column='Id_TUser', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(db_column='Id_Trabajador', primary_key=True, serialize=False)),
                ('num_doctrab', models.CharField(db_column='Num_DocTrab', max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('detalles_direccion', models.CharField(blank=True, db_column='Detalles_direccion', max_length=255, null=True)),
                ('id_municipio', models.ForeignKey(blank=True, db_column='Id_Municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.municipio')),
                ('id_tdoc', models.ForeignKey(blank=True, db_column='Id_TDoc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.tdocumento')),
                ('id_tuser', models.ForeignKey(blank=True, db_column='Id_TUser', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tipousuario')),
            ],
            options={
                'db_table': 'trabajador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(db_column='Id_Usuario', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='Usuario', max_length=50, unique=True)),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=255)),
                ('id_trabajador', models.ForeignKey(blank=True, db_column='Id_Trabajador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.trabajador')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='trabajador',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='Id_Usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios'),
        ),
    ]
