# Generated by Django 5.0.6 on 2024-06-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
