# Generated by Django 5.0.6 on 2024-06-25 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_fpago', models.AutoField(db_column='Id_FPago', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'forma_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id_mpago', models.AutoField(db_column='Id_MPago', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'medio_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(blank=True, db_column='Fecha_emision', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='Fecha_vencimiento', null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='Id_Cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.cliente')),
                ('id_trabajador', models.ForeignKey(blank=True, db_column='Id_trabajador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.trabajador')),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesCotizacion',
            fields=[
                ('id_dcotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('subtotal_prodc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_cotizacion', models.ForeignKey(blank=True, db_column='Id_Cotizacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transacciones.cotizacion')),
                ('id_producto', models.ForeignKey(blank=True, db_column='Id_Producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
            ],
            options={
                'db_table': 'detalles_cotizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('n_lote', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_Producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
                ('id_proveedor', models.ForeignKey(blank=True, db_column='id_Proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.proveedor')),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id_proforma', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(blank=True, db_column='Fecha_emision', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='Fecha_vencimiento', null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='Id_Cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.cliente')),
                ('id_fpago', models.ForeignKey(blank=True, db_column='Id_FPago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transacciones.formapago')),
                ('id_mpago', models.ForeignKey(blank=True, db_column='Id_MPago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transacciones.mediopago')),
                ('id_trabajador', models.ForeignKey(blank=True, db_column='Id_trabajador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.trabajador')),
            ],
            options={
                'db_table': 'proforma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesProforma',
            fields=[
                ('id_dproforma', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('subtotal_prodprof', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='Id_Producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
                ('id_proforma', models.ForeignKey(blank=True, db_column='Id_Proforma', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transacciones.proforma')),
            ],
            options={
                'db_table': 'detalles_proforma',
                'managed': True,
            },
        ),
    ]
