# Generated by Django 5.0.6 on 2024-06-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detallescotizacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detallesproforma',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='formapago',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mediopago',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proforma',
            options={'managed': False},
        ),
    ]
