# Generated by Django 5.0.6 on 2024-06-25 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(db_column='Id_Cat', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(db_column='Id_Producto', primary_key=True, serialize=False)),
                ('cod_producto', models.CharField(db_column='Cod_Producto', max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=100, null=True)),
                ('stock', models.IntegerField(blank=True, db_column='Stock', null=True)),
                ('stock_min', models.IntegerField(blank=True, db_column='Stock_min', null=True)),
                ('stock_max', models.IntegerField(blank=True, db_column='Stock_max', null=True)),
                ('precio_venta', models.DecimalField(blank=True, db_column='precio_Venta', decimal_places=2, max_digits=10, null=True)),
                ('id_cat', models.ForeignKey(blank=True, db_column='Id_Cat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.categoria')),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
    ]
