# Generated by Django 5.0.6 on 2024-06-25 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='Id_Cliente', primary_key=True, serialize=False)),
                ('n_doccl', models.CharField(db_column='N_DocCl', max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('detalles_direccion', models.CharField(blank=True, db_column='Detalles_direccion', max_length=255, null=True)),
                ('id_municipio', models.ForeignKey(blank=True, db_column='Id_Municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.municipio')),
                ('id_tcont', models.ForeignKey(blank=True, db_column='Id_TCont', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.tcontribuyente')),
                ('id_tdoc', models.ForeignKey(blank=True, db_column='Id_TDoc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.tdocumento')),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(db_column='Id_Proveedor', primary_key=True, serialize=False)),
                ('num_docpro', models.CharField(db_column='Num_DocPro', max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('detalles_direccion', models.CharField(blank=True, db_column='Detalles_direccion', max_length=255, null=True)),
                ('id_municipio', models.ForeignKey(blank=True, db_column='Id_Municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.municipio')),
                ('id_tcont', models.ForeignKey(blank=True, db_column='Id_TCont', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.tcontribuyente')),
                ('id_tdoc', models.ForeignKey(blank=True, db_column='Id_TDoc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.tdocumento')),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
    ]
