# Generated by Django 5.0.6 on 2024-06-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False},
        ),
    ]
